# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Online_ChatRoom_HUNAU.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):
    def __init__(self, name: str = None, number: int = None):
        """

        :rtype: object
        """
        super(Ui_Form, self).__init__()

        self.setWindowModality(QtCore.Qt.ApplicationModal)
        self.resize(640, 480)
        self.setMouseTracking(True)
        self.sendingButton = QtWidgets.QPushButton(self)
        self.sendingButton.setGeometry(QtCore.QRect(570, 460, 75, 23))
        self.sendingButton.setAutoDefault(True)
        self.sendingButton.setObjectName("sendingButton")
        self.exitButton = QtWidgets.QPushButton(self)
        self.exitButton.setGeometry(QtCore.QRect(500, 460, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.fontButton = QtWidgets.QPushButton(self)
        self.fontButton.setGeometry(QtCore.QRect(0, 220, 41, 23))
        self.fontButton.setObjectName("fontButton")
        self.emojButton = QtWidgets.QPushButton(self)
        self.emojButton.setGeometry(QtCore.QRect(40, 220, 41, 23))
        self.emojButton.setObjectName("emojButton")
        self.screenShotButton = QtWidgets.QPushButton(self)
        self.screenShotButton.setGeometry(QtCore.QRect(80, 220, 41, 23))
        self.screenShotButton.setAutoDefault(True)
        self.screenShotButton.setObjectName("screenShotButton")
        self.videoButton = QtWidgets.QPushButton(self)
        self.videoButton.setGeometry(QtCore.QRect(120, 220, 75, 23))
        self.videoButton.setObjectName("videoButton")
        self.fileSenderButton = QtWidgets.QPushButton(self)
        self.fileSenderButton.setGeometry(QtCore.QRect(190, 220, 75, 23))
        self.fileSenderButton.setObjectName("fileSenderButton")
        self.messageHistoryButton = QtWidgets.QPushButton(self)
        self.messageHistoryButton.setGeometry(QtCore.QRect(570, 220, 75, 23))
        self.messageHistoryButton.setAutoDefault(True)
        self.messageHistoryButton.setObjectName("messageHistoryButton")
        self.messageEide = QtWidgets.QPlainTextEdit(self)
        self.messageEide.setGeometry(QtCore.QRect(0, 240, 641, 221))
        self.messageEide.setObjectName("messageEide")
        self.messageView = QtWidgets.QTextBrowser(self)
        self.messageView.setGeometry(QtCore.QRect(0, 0, 641, 221))
        self.messageView.setObjectName("messageView")

        self.retranslateUi(name, number)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, name: str = None, number: int = None) -> None:
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(str(name) + '(' + str(number) + ')')
        self.sendingButton.setText(_translate("Form", "发送"))
        self.exitButton.setText(_translate("Form", "关闭"))
        self.fontButton.setText(_translate("Form", "字体"))
        self.emojButton.setText(_translate("Form", "表情"))
        self.screenShotButton.setText(_translate("Form", "截图"))
        self.videoButton.setText(_translate("Form", "视频通话"))
        self.fileSenderButton.setText(_translate("Form", "文件发送"))
        self.messageHistoryButton.setText(_translate("Form", "消息记录"))


